### ISSUE TITLE
Implementing Constructor #1 // Matrix(int m, int n, double s)

### ISSUE THREAD

**Issue by Atunez** [AgileAppstate/javatrix-eigentrix#2]
Implement the following constructor:

Matrix(int m, int n, double s)
Construct an m-by-n constant matrix.

Estimate: 10 minutes.

**Comment by fenwickjb** [comment]
10 minutes.

**Comment by Atunez** [comment]
Changes Merged, Check https://github.com/AgileAppstate/javatrix-eigentrix/pull/12/commits/59d8d31b0e79a59df271f1786f6eaf3306b43557
