### ISSUE TITLE
Testing Constructor #1 // Matrix(int m, int n, double s)

### ISSUE THREAD

**Issue by Atunez** [AgileAppstate/javatrix-eigentrix#3]
Test constructor built in:

- [ ] https://github.com/AgileAppstate/javatrix-eigentrix/issues/2

Estimate: 10 minutes

**Comment by fenwickjb** [comment]
20 minutes so far...
Had to copy over barebones JUnit testing infrastructure (makefile, junit.jar, etc.)
Spent a bit of time thinking over how to handle negative tests (improper parameter input values)...

**Comment by fenwickjb** [comment]
60 minutes figuring out style checker modifications. (Ugh.)

**Comment by Atunez** [comment]
Changes Merged, Check https://github.com/AgileAppstate/javatrix-eigentrix/pull/12/commits/59d8d31b0e79a59df271f1786f6eaf3306b43557
